### ISSUE TITLE
NTS version 2.0 for PostGis

### ISSUE THREAD

**Issue by YohDeadfall** [NetTopologySuite/NetTopologySuite.IO.PostGis#10]
We are updating our EF Core provider to version 3.0, but we handle geometry in the driver plugin using this library. How should we update our NTS driver plugin to support version 2.0 and use it for EFCore.PG 3.0?  I have found no preview package version 2.0 of NetTopologySuite.IO.PostGis on NuGet. If you're not going to support it anymore, we will all required stuff in out library.

/cc @roji

**Comment by airbreather** [comment]
> How should we update our NTS driver plugin to support version 2.0 and use it for EFCore.PG 3.0? I have found no preview package version 2.0 of NetTopologySuite.IO.PostGis on NuGet. If you're not going to support it anymore, we will all required stuff in out library.

I'm going through and updating the I/O libraries to v2 now.

**Comment by YohDeadfall** [comment]
When are you going to publish a preview? By the way, who are users of this library? If only Npgsql uses it or there are not so much of them, we could implement all required stuff in our handler directly. Does it make sense?

**Comment by airbreather** [comment]
> By the way, who are users of this library? If only Npgsql uses it or there are not so much of them, we could implement all required stuff in our handler directly.

@FObermaier any insights on this question?  Anything that means we have to maintain less code sounds great to me...

**Comment by peetw** [comment]
We use this library over at [NHibernate.Spatial](https://github.com/nhibernate/NHibernate.Spatial) for the PostGIS adaptor.

**Comment by roji** [comment]
@peetw I'm curious, does that mean that you're not using Npgsql to talk to PostgreSQL, but implement the PostgreSQL wire protocol yourselves?

**Comment by airbreather** [comment]
> When are you going to publish a preview?

Published: https://www.nuget.org/packages/NetTopologySuite.IO.PostGis/2.0.0-pre001

**Comment by peetw** [comment]
@roji We use this library to convert GeoAPI/NTS geometries to/from byte arrays (see the `FromGeometry` and `ToGeometry` methods [here](https://github.com/nhibernate/NHibernate.Spatial/blob/master/NHibernate.Spatial.PostGis/Type/PostGisGeometryType.cs)). These are then passed to/from the database via NHibernate and Npgsql. We already have a dependency on Npgsql, so not too fussed whether this code moves there, but keeping it as a separate lib would seem to make more sense to me.

**Comment by roji** [comment]
@peetw hmm, to be sure I understand... Npgsql itself knows how to write geometry types to PostGIS [via a plugin](http://www.npgsql.org/doc/types/nts.html), so an application using Npgsql shouldn't need to worry about serialization - the Npgsql plugin does that for them. Are you using Npgsql, but bypassing the plugin in some way, handling serialization yourself?

**Comment by peetw** [comment]
@roji NHibernate.Spatial is an extension to NHibernate (an ORM) that allows spatial columns to be mapped correctly by NHibernate, for any database type (e.g. MS SQL, MySQL, PostgreSQL, etc.). End users are not using Npgsql directly.

**Comment by roji** [comment]
I understand that, but assuming Npgsql is the one actually talking to PostgreSQL, shouldn't it also be the one to take care of spatial serialization?

**Comment by FObermaier** [comment]
Npgsql is not the only postgresql provider for .net. Therefore I'd prefer the code to stay here.

**Comment by roji** [comment]
@FObermaier it's definitely not a problem for me if you guys want to keep maintaining this - was mainly trying to understand the situation and possibly propose to reduce your workload.

PS Again out of curiosity, is there another driver using NetTopologySuite.IO.PostGis (e.g. Devart?)

**Comment by FObermaier** [comment]
@roji I don't know if anyone uses this library with Devart's dotConnect provider, but they could.

**Comment by YohDeadfall** [comment]
Closing since version 2.0.0 was released. Thanks!
