### ISSUE TITLE
Empty polygon representation is rejected by PostgreSQL

### ISSUE THREAD

**Issue by roji** [NetTopologySuite/NetTopologySuite.IO.PostGis#14]
When writing:

```c#
XX000: WKB structure does not match expected size!
Data:
  Severity: ERROR
  InvariantSeverity: ERROR
  SqlState: XX000
  MessageText: WKB structure does not match expected size!
  File: lwgeom_pg.c
  Line: 250
  Routine: pg_error
```

Originally flagged in https://github.com/npgsql/npgsql/issues/3467

**Comment by roji** [comment]
@FObermaier thanks for the quick fix! Hopefully a 2.0.1 nuget can be released soon :)

**Comment by FObermaier** [comment]
@airbreather, did you have a look at the latest changes? As some semantics changed I'd go with v2.1 rather than v2.0.1
I didn't care too much about the travis-ci integration, I'd prefer to move to github-actions.

**Comment by airbreather** [comment]
> @airbreather, did you have a look at the latest changes?

Looks fine to me, though I don't use PostGIS on a regular basis, so I can easily miss things.

> I didn't care too much about the travis-ci integration, I'd prefer to move to github-actions.

I just don't like seeing too much of this, is all:
![image](https://user-images.githubusercontent.com/3792815/105357599-096fbc00-5bc3-11eb-8238-f68b1c664944.png)

**Comment by roji** [comment]
@airbreather @FObermaier any chance of getting a 2.0.1 nuget with the fix? It's been a while...

**Comment by roji** [comment]
Note similarity (possible identity) with https://github.com/NetTopologySuite/NetTopologySuite.IO.SqlServerBytes/issues/14 for SQL Server.

**Comment by FObermaier** [comment]
> @airbreather @FObermaier any chance of getting a 2.0.1 nuget with the fix? It's been a while...

@roji, it is live.

**Comment by roji** [comment]
Thanks @FObermaier!
